version: '3.7'
services:
  pong-service:
    container_name: pong_service
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pong_service
    environment:
      API_PORT: 3005
      PING_GRPC_SERVER_URL: 172.40.0.8
      PONG_GRPC_SERVER_URL: 172.40.0.6
    ports:
      - "3005:3005"
    command: npm run nest:start
    networks:
      ping_pong_network:
        ipv4_address: 172.40.0.6
    restart: unless-stopped

networks:
  ping_pong_network:
    driver: bridge
    name: ping_pong_network
    ipam:
      config:
        - subnet: 172.40.0.0/16
